networks:
  default:
    name: transcendence
    external: false

services:
  redis:
    image: 'redis:6.2-alpine'
    container_name: redis
    
  celery_worker:
    build:
      context: ./
      dockerfile: ./celery/Dockerfile
    image: django_celery_example_celery_worker
    command: /start-celeryworker
    container_name: celery_worker
    depends_on:
      - redis
      - db
      - tournaments
    volumes:
      - ./tournaments:/app
    env_file:
      - .env

  celery_beat:
    build:
      context: ./
      dockerfile: ./celery/Dockerfile
    image: django_celery_example_celery_beat
    command: /start-celerybeat
    container_name: celery_beat
    depends_on:
      - redis
      - db
      - tournaments
    volumes:
      - ./tournaments:/app
    env_file:
      - .env

  flower:
    build:
      context: ./
      dockerfile: ./celery/Dockerfile
    image: django_celery_example_celery_flower
    command: /start-flower
    container_name: flower
    depends_on:
      - redis
      - db
      - tournaments
    ports:
      - 5557:5555
    volumes:
      - ./tournaments:/app
    env_file:
      - .env

  migrations:
    container_name: migrations
    build: ./migrator
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DEBUG=${DEBUG}
    env_file:
      - .env
    volumes:
      - ./usermodel:/app/usermanagement/usermodel
      - ./usermanagement:/app/usermanagement
      - ./matches:/app/matches

  db:
    container_name: db
    restart: always
    image: postgres:13
    environment:
      POSTGRES_DB: transcendence
      POSTGRES_USER: transcendence
      POSTGRES_PASSWORD: 1234
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d transcendence -U transcendence"]
      interval: 10s
      timeout: 60s
      retries: 5
      start_period: 80s 

  gateway:
    restart: always
    container_name: gateway
    build: ./gateway
    ports:
      - "8000:8000"
    volumes:
      - ${LOGSTASH_FOLDER}${GATEWAY_LOG}:/var/log/${GATEWAY_LOG}
      - ${DJANGO_SCRIPT}:/start.sh
      - ./gateway:/app
      - ./frontend:/app/frontend

    env_file:
      - .env
    environment:
      - DEBUG=${DEBUG}
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  usermanagement:
    restart: always
    depends_on:
      - migrations
    container_name: usermanagement
    build: ./usermanagement
    volumes:
      - ${LOGSTASH_FOLDER}${USER_LOG}:/var/log/${USER_LOG}
      - ${DJANGO_SCRIPT}:/start.sh
      - ./usermanagement:/app
      - ./usermodel:/app/usermodel
    environment:
      - DEBUG=${DEBUG}
    env_file:
      - .env

  chat:
    restart: always

    depends_on:
      - migrations
    container_name: chat
    build: ./chat
    volumes:
      - ${LOGSTASH_FOLDER}${TOURNAMENT_LOG}:/var/log/${TOURNAMENT_LOG}
      - ${DJANGO_SCRIPT}:/start.sh
      - ./chat:/app

    env_file:
      - .env
    environment:
      - APP=chatapp
      - DEBUG=${DEBUG}

  tournaments:
    depends_on:
      - redis
      - db
    container_name: tournaments
    build: ./tournaments
    volumes:
      - ${LOGSTASH_FOLDER}${TOURNAMENT_LOG}:/var/log/${TOURNAMENT_LOG}
      - ./tournaments:/app
      - ./usermodel:/app/usermodel
    env_file:
      - .env
    environment:
      - APP=tournaments
      - DEBUG=${DEBUG}
      - TOURNAMENTS_FOLDER=${TOURNAMENTS_FOLDER}
    ports:
      - 8001:8001

  twofactor:
    restart: always

    depends_on:
      db:
        condition: service_healthy
    container_name: twofactor
    build: ./twofactor
    volumes:
      - ${LOGSTASH_FOLDER}${TWOFACTOR_LOG}:/var/log/${TWOFACTOR_LOG}
      - ${DJANGO_SCRIPT}:/start.sh
    env_file:
      - .env
    environment:
      - APP=twofactor
      - DEBUG=${DEBUG}

  # Monitoring Container


  prometheus:
    image: prom/prometheus:v2.53.1
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
    volumes:
      - ./Prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml:ro
      - prometheus-data:/prometheus
  grafana:
    image: grafana/grafana:11.1.1-ubuntu
    container_name: grafana
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=newadmin
    volumes:
      - grafana-data:/var/lib/grafana


  setup:
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    volumes:
      - certs:/usr/share/elasticsearch/config/certs
      - ./setup/setup_script.sh:/setup_script.sh
      - ./setup/grafana_script.sh:/grafana_script.sh
      - ./setup/ELK_script.sh:/ELK_script.sh
      - ./ELK:/ELK
      - ./Grafana/gateway_dashboard.json:/gateway_dashboard.json
#    user: "0"
    environment:
      - SLACK_HOOK=${SLACK_HOOK}
    env_file:
      - .env
    command: >
      bash /setup_script.sh
    healthcheck:
      test: ["CMD-SHELL", "[ -f config/certs/es01/es01.crt ]"]
      interval: 1s
      timeout: 5s
      retries: 120

  es01:
    restart: always

    depends_on:
      setup:
        condition: service_healthy
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    labels:
      co.elastic.logs/module: elasticsearch
    container_name: elasticsearch
    volumes:
      - certs:/usr/share/elasticsearch/config/certs
      - esdata01:/usr/share/elasticsearch/data
    environment:
      - node.name=es01
      - cluster.name=${CLUSTER_NAME}
      - discovery.type=single-node
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - bootstrap.memory_lock=true
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=true
      - xpack.security.http.ssl.key=certs/es01/es01.key
      - xpack.security.http.ssl.certificate=certs/es01/es01.crt
      - xpack.security.http.ssl.certificate_authorities=certs/ca/ca.crt
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.key=certs/es01/es01.key
      - xpack.security.transport.ssl.certificate=certs/es01/es01.crt
      - xpack.security.transport.ssl.certificate_authorities=certs/ca/ca.crt
      - xpack.security.transport.ssl.verification_mode=certificate
      - xpack.license.self_generated.type=${LICENSE}
    mem_limit: ${ES_MEM_LIMIT}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s --cacert config/certs/ca/ca.crt https://localhost:9200 | grep -q 'missing authentication credentials'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120

  logstash:
    restart: always

    depends_on:
      es01:
        condition: service_healthy
      kibana:
        condition: service_healthy
    image: docker.elastic.co/logstash/logstash:${STACK_VERSION}
    labels:
      co.elastic.logs/module: logstash
    container_name: logstash
#    user: root

    volumes:
      - certs:/usr/share/logstash/certs
      - ./ELK/logstash:/usr/share/logstash/pipeline:ro
      - logstashdata01:/var/log
    environment:
      - xpack.monitoring.enabled=false
      - ELASTIC_USER=elastic
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - ELASTIC_HOSTS=https://es01:9200
    env_file:
      - .env

  kibana:
    restart: always
    ports:
      - ${KIBANA_PORT}:5601
    depends_on:
      es01:
        condition: service_healthy
    image: docker.elastic.co/kibana/kibana:${STACK_VERSION}
    labels:
      co.elastic.logs/module: kibana
    volumes:
      - certs:/usr/share/kibana/config/certs
      - kibanadata:/usr/share/kibana/data

    container_name: kibana
    environment:
      - SERVERNAME=kibana
      - ELASTICSEARCH_HOSTS=https://es01:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=${KIBANA_PASSWORD}
      - ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES=config/certs/ca/ca.crt
      - XPACK_SECURITY_ENCRYPTIONKEY=${ENCRYPTION_KEY}
      - XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY=${ENCRYPTION_KEY}
      - XPACK_REPORTING_ENCRYPTIONKEY=${ENCRYPTION_KEY}

    mem_limit: ${KB_MEM_LIMIT}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s -I http://localhost:5601 | grep -q 'HTTP/1.1 302 Found'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120

  blockchain:
    depends_on:
      - migrations
    build:
      context: ./blockchain
    container_name: blockchain
    ports:
      - "8545:8545"
    env_file:
      - .env
    #restart: always
    volumes:
      - ${TOURNAMENTS_FOLDER}${TOURNAMENT_LOG}:/var/log/${TOURNAMENT_LOG}
      - ./blockchain:/app
  frontend:
    container_name: frontend
    build:
      context: ./frontend

volumes:
  certs:
    driver: local
    driver_opts:
      type: none
      device: ${CERTS_FOLDER}
      o: bind
  esdata01:
    driver: local
    driver_opts:
      type: none
      device: ${ESDATA_FOLDER}
      o: bind
  kibanadata:
    driver: local
    driver_opts:
      type: none
      device: ${KIBANA_FOLDER}
      o: bind
  logstashdata01:
    driver: local
    driver_opts:
      type: none
      device: ${LOGSTASH_FOLDER}
      o: bind
  postgres-data:
    driver: local
    driver_opts:
      type: none
      device: ${POSTGREE_FOLDER}
      o: bind
  prometheus-data:
    driver: local
    driver_opts:
      type: none
      device: ${PROMETHEUS_FOLDER}
      o: bind
  grafana-data:
    driver: local
    driver_opts:
      type: none
      device: ${GRAFANA_FOLDER}
      o: bind
  blockchain_data:
    driver: local
    driver_opts:
      type: none
      device: ${BLOCKCHAIN_FOLDER}
      o: bind
  shared:
    driver: local
    driver_opts:
      type: none
      device: ${SHARED_FOLDER}
      o: bind
  
